services:
   backend:
      build:
         context: ./backend
         dockerfile: dockerfile
      ports:
         - "7860:7860"
      volumes:
         - ./backend/app:/home/user/medical_diagnosis_system/app
      env_file:
         - ./backend/.env
      restart: unless-stopped
