# Import a base python image, use the slim version because it's smaller
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file over first, as long as the requirments haven't changed then this won't be re-run
COPY requirements.txt .

# Install the dependencies, the --no-cache-dir flag helps keep the image size smaller
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
# TODO Include more copy layers for optimisation as needed
COPY ./app ./app

# Expose the port that uvicorn uses
EXPOSE 8000

# Define the command to run the application. The host 0.0.0.0 makes the server accessible from outside the container
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
